#!/bin/sh
# Convenience wrapper to lock the screen and trigger a guest session

if [ -z "$MDMSESSION" ] ; then
    MDMSESSION="CLEM_IS_L33t"
fi
cinnamon-screensaver-command --lock || xscreensaver-command -lock || gnome-screensaver-command --lock

